/** The sample tree written into an empty FilesApi. */
export const SEED: Record<string, string> = {
  "/welcome.md": [
    "# Welcome",
    "",
    "A Markdown editor running entirely in the browser: Eclipse Theia over a `FilesApi`.",
    "",
    "## Getting started",
    "",
    "Open a file from the explorer, edit it, and save with Ctrl+S.",
    "",
    "## Files",
    "",
    "Everything you see is served by `@statewalker/webrun-files`.",
    "",
    "## Markdown",
    "",
    "Use *Markdown: Open Preview to the Side* and *Markdown: Show Outline*.",
    "",
  ].join("\n"),
  "/notes/ideas.md": [
    "# Ideas",
    "",
    "- A shell for the mesh",
    "- Components installed at runtime",
    "",
    "Plain line",
    "",
    "Another line",
    "",
  ].join("\n"),
  "/docs/cheatsheet.md": [
    "# Cheatsheet",
    "",
    "| Syntax | Result |",
    "|---|---|",
    "| `**bold**` | **bold** |",
    "| `_italic_` | _italic_ |",
    "| `[link](https://example.com)` | [link](https://example.com) |",
    "",
    "```js",
    "# not a heading",
    "```",
    "",
  ].join("\n"),
};
